data:
  root_path: ./data/ # path to the parent folder of your dataset
  dataset_name: imagenet1k  # Change to your dataset name if needed
  train_subset_file: meta/in1k_subset10.0%_seed0_train.txt
  test_subset_file: null
  batch_size_per_replica: 256
  num_workers: 8
  pin_memory: True
  augmentation:
    crop_size: 224
    img_size: 256
    interpolation: 3
    use_gaussian_blur: False
    use_horizontal_flip: False
    use_color_distortion: False
    color_jitter_strength: 0.0
knn:
  knn_k: 20
  knn_t: 0.07
  num_classes: 1000
  feature_strategy: 
    - lastPOOL
    - concatPOOL4
  use_amp: False
  sim_chunk_size: 4096
framework:
  name: knn
model:
  pretrained_weights: # YOUR PATH HERE
  model_name: vit_base
  patch_size: 16
  num_classes: 1000
logging:
  log_dir: logs/knn_ijepa_vitb_in1k/
  verbose: True




  